# syntax=docker/dockerfile:1.7

FROM restic/restic:0.19.1@sha256:136600b6ff6843d61d355f7f71f460a166429f35de6fd11b568fece3c9a4d510 AS restic

FROM postgres:17.6-alpine
RUN apk add --no-cache ca-certificates
COPY --from=restic /usr/bin/restic /usr/local/bin/restic
COPY scripts/backup /opt/platform/backup
WORKDIR /opt/platform
ENTRYPOINT ["sh"]
