import {
  DJ_STUDIO_PERMISSION_KEYS,
  type DjStudioPermissionKey,
} from '@/domains/dj-studio/permissions/permission-keys'
import { SYSTEM_ROLE_KEYS } from '@/core/modules/roles/constants/system-role-keys'

/**
 * Approved default Role → DJ Studio Domain Permission grants.
 * Extends system Roles without changing Core Role meanings.
 */
export const DJ_STUDIO_SYSTEM_ROLE_PERMISSION_POLICY = {
  [SYSTEM_ROLE_KEYS.OWNER]: [
    DJ_STUDIO_PERMISSION_KEYS.LIBRARY_READ,
    DJ_STUDIO_PERMISSION_KEYS.LIBRARY_MANAGE,
    DJ_STUDIO_PERMISSION_KEYS.PLAYLISTS_READ,
    DJ_STUDIO_PERMISSION_KEYS.PLAYLISTS_MANAGE,
  ],
  [SYSTEM_ROLE_KEYS.ADMIN]: [
    DJ_STUDIO_PERMISSION_KEYS.LIBRARY_READ,
    DJ_STUDIO_PERMISSION_KEYS.LIBRARY_MANAGE,
    DJ_STUDIO_PERMISSION_KEYS.PLAYLISTS_READ,
    DJ_STUDIO_PERMISSION_KEYS.PLAYLISTS_MANAGE,
  ],
  [SYSTEM_ROLE_KEYS.MANAGER]: [
    DJ_STUDIO_PERMISSION_KEYS.LIBRARY_READ,
    DJ_STUDIO_PERMISSION_KEYS.LIBRARY_MANAGE,
    DJ_STUDIO_PERMISSION_KEYS.PLAYLISTS_READ,
    DJ_STUDIO_PERMISSION_KEYS.PLAYLISTS_MANAGE,
  ],
  [SYSTEM_ROLE_KEYS.MEMBER]: [
    DJ_STUDIO_PERMISSION_KEYS.LIBRARY_READ,
    DJ_STUDIO_PERMISSION_KEYS.LIBRARY_MANAGE,
    DJ_STUDIO_PERMISSION_KEYS.PLAYLISTS_READ,
    DJ_STUDIO_PERMISSION_KEYS.PLAYLISTS_MANAGE,
  ],
  [SYSTEM_ROLE_KEYS.VIEWER]: [
    DJ_STUDIO_PERMISSION_KEYS.LIBRARY_READ,
    DJ_STUDIO_PERMISSION_KEYS.PLAYLISTS_READ,
  ],
} as const satisfies Record<string, readonly DjStudioPermissionKey[]>
