import {
  PERMISSION_KEYS,
  type PermissionKey,
} from '@/core/modules/permissions/constants/permission-keys'
import {
  SYSTEM_ROLE_KEYS,
  type SystemRoleKey,
} from '@/core/modules/roles/constants/system-role-keys'

export const SYSTEM_ROLE_PERMISSION_POLICY = {
  [SYSTEM_ROLE_KEYS.OWNER]: Object.values(PERMISSION_KEYS),
  [SYSTEM_ROLE_KEYS.ADMIN]: [
    PERMISSION_KEYS.ORGANIZATIONS_READ,
    PERMISSION_KEYS.ORGANIZATIONS_UPDATE,
    PERMISSION_KEYS.MEMBERSHIPS_READ,
    PERMISSION_KEYS.MEMBERSHIPS_SUSPEND,
    PERMISSION_KEYS.MEMBERSHIPS_RESTORE,
    PERMISSION_KEYS.MEMBERSHIPS_REMOVE,
    PERMISSION_KEYS.MEMBERSHIPS_CHANGE_ROLE,
    PERMISSION_KEYS.INVITATIONS_READ,
    PERMISSION_KEYS.INVITATIONS_CREATE,
    PERMISSION_KEYS.INVITATIONS_REVOKE,
    PERMISSION_KEYS.INVITATIONS_RESEND,
  ],
  [SYSTEM_ROLE_KEYS.MANAGER]: [
    PERMISSION_KEYS.ORGANIZATIONS_READ,
    PERMISSION_KEYS.MEMBERSHIPS_READ,
  ],
  [SYSTEM_ROLE_KEYS.MEMBER]: [PERMISSION_KEYS.ORGANIZATIONS_READ],
  [SYSTEM_ROLE_KEYS.VIEWER]: [PERMISSION_KEYS.ORGANIZATIONS_READ],
} as const satisfies Record<SystemRoleKey, readonly PermissionKey[]>
