export const DJ_STUDIO_ERROR_CODES = {
  UNAUTHENTICATED: 'DJ_STUDIO_UNAUTHENTICATED',
  FORBIDDEN: 'DJ_STUDIO_FORBIDDEN',
  NO_ACTIVE_ORGANIZATION: 'DJ_STUDIO_NO_ACTIVE_ORGANIZATION',
  TRACK_NOT_FOUND: 'DJ_STUDIO_TRACK_NOT_FOUND',
  LIBRARY_ITEM_NOT_FOUND: 'DJ_STUDIO_LIBRARY_ITEM_NOT_FOUND',
  LIBRARY_ITEM_IN_USE: 'DJ_STUDIO_LIBRARY_ITEM_IN_USE',
  PLAYLIST_NOT_FOUND: 'DJ_STUDIO_PLAYLIST_NOT_FOUND',
  PLAYLIST_ITEM_NOT_FOUND: 'DJ_STUDIO_PLAYLIST_ITEM_NOT_FOUND',
  TAG_NOT_FOUND: 'DJ_STUDIO_TAG_NOT_FOUND',
  TAG_NAME_CONFLICT: 'DJ_STUDIO_TAG_NAME_CONFLICT',
  VALIDATION_ERROR: 'DJ_STUDIO_VALIDATION_ERROR',
  PROFILE_NOT_FOUND: 'DJ_STUDIO_PROFILE_NOT_FOUND',
} as const

export type DjStudioErrorCode =
  (typeof DJ_STUDIO_ERROR_CODES)[keyof typeof DJ_STUDIO_ERROR_CODES]

export class DjStudioError extends Error {
  readonly code: DjStudioErrorCode

  constructor(code: DjStudioErrorCode, message?: string) {
    super(message ?? code)
    this.name = 'DjStudioError'
    this.code = code
  }
}
